version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
    environment:
      DATABASE_HOST: db
      DATABASE_USER: test_user
      DATABASE_PASSWORD: test_password
      DATABASE_NAME: test_db
    depends_on:
      db:
        condition: service_healthy
